<template>
  <div class="chartElem">
    <div class="row">
      <highcharts class="chart" :options="chartOptions"></highcharts>
        </div>
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {
       action: '/get_temper_info',     
      chartOptions: {    
// Options will be generated by AJAX get
      }
    }
  },

  mounted() {     
           axios.get(this.action).then((response) => {
     this.chartOptions = response.data; // Set chartOptions
      });            
   },

  created () {  
  },
  watch: {
  }
}
</script>

